## defaults for _all_ profiles
[default]
address = "0.0.0.0"

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
port = 2137
## only the `json` key from `default` will be overridden; `forms` will remain

## set only when the `nyc` profile is selected
[nyc]
port = 2137

## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]
port = 2137